language: ruby
gemfile:
  - Gemfile
  # i can't find a way to use the same Gemfile and just specify --without varint
  - Gemfile.no_varint
rvm:
  - "1.8.7"
  - "1.9.3"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
matrix:
  exclude:
    # can't use the varint extension in jruby runs
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
